name: unixtime
description: DateTime extension for treating Unix Time
version: 1.0.0
homepage: https://github.com/ashphy/unixtime.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  timezone: ^0.9.0
